### ISSUE TITLE
Change language Switcher

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#101]
The language switcher on the main site needs to change visually and look like this:
https://projects.invisionapp.com/d/main#/console/14008200/300085215/preview

the languages should be represented by their 2-letter acronyms:
עב - עברית
En - אנגלית
Ру - רוסית

(שים לב שזה לא אותיות אנגליות פי וואי, אלה אותיות רוסיות שנראות דומה(

השפה המושמשת צריכה להיות מודגשת.

**Comment by nirgoldberg** [comment]
Done.
