### ISSUE TITLE
Synagogue Gallery Prayer Email

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#18]
When sending an email with personal prayer, add this text:

ניתן להשתמש בטקסט שנשלח אליך לשימוש אישי בלבד, בכפוף לחוק זכויות יוצרים.
Text sent to you is for your personal use only and is subject to copyright law.

**Comment by nuritgazit** [comment]
This issue is already done, I'm closing it
