### ISSUE TITLE
Add year indicator to event start / end dates

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#20]
We do not currently display the date compeltely. The years are currently designated by 2 digits or no indicator of year at all.
We need to have a year in **all** dates

**Comment by ibanner** [comment]
Pull request #26 still pending review :)

**Comment by nirgoldberg** [comment]
Done.

**Comment by nuritgazit** [comment]
@TheGrandVizier Same here - I think this should be closed
