### ISSUE TITLE
Separate Exhibitions and Events

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#23]
Needs design for hebrew and english

temporary:
![menu](https://cloud.githubusercontent.com/assets/15191989/24197869/14d305be-0f0c-11e7-8d99-21ee11782e37.png)

**Comment by TheGrandVizier** [comment]
@nuritgazit @Libisch 
Can you guys textually describe what you actually want here?

**Comment by nuritgazit** [comment]
I want to separate between Exhibitions (all types of them - which are marked green in the print screen above) and Events (all types of them - which are marked blue) and to have 2 separated links - Exhibitions and Events in the header. Clearer?

**Comment by nirgoldberg** [comment]
Done.

**Comment by nuritgazit** [comment]
Great!
@nirgoldberg, can you change places between them, so that Exhibitions would appear first (most right in Hebrew and most left in English)?

**Comment by nirgoldberg** [comment]
Done.
@TheGrandVizier, please approve deployment to live env.
