### ISSUE TITLE
Problems cloning this project

### ISSUE THREAD

**Issue by ibanner** [Beit-Hatfutsot/wp-bh#24]
@TheGrandVizier / @nirgoldberg - I'm having a really hard time cloning this project to my localhost. The files are OK but the DB on `test.bh.org.il` is huge and every attempt I make to import the DB ends up crashing. As most of the UI is built with ACF, the `wp_options` table is gigantic, the there's a specific row that brakes the process every time.

For obvious reasons I prefer not to push directly to `master`. 

For the time being I can't really make progress on the issues @nuritgazit assigned to me. 

Any advice?

**Comment by nuritgazit** [comment]
thanks, @ibanner. @nirgoldberg will be here tomorrow and will look into it

**Comment by ibanner** [comment]
Already done (closing this issue).
