### ISSUE TITLE
Gift Card iFrame goes crazy

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#25]
ניר, משהו התחרבש ב iframe הזה (כלום לא השתנה מלבד הקישור שמפנה לעמוד: היה מההאדר ועכשיו מעמוד רכישת כרטיסים).
http://www.bh.org.il/he/gift-card/

FYI @TheGrandVizier @Libisch

**Comment by nirgoldberg** [comment]
@Libisch, this page was edited and some values changed within the iframe.
Please copy and paste from test env. to live in order to restore it.

**Comment by Libisch** [comment]
Copied and restored.
