### ISSUE TITLE
Some Hebrew pages do not have a navigation menu displayed

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#29]
Specifically, the following pages cause the navigation menu to disappear:

סדרות והשתלמויות
תוכנות חינוכיות
המחלקה לתוכניות צה"ל

Repro:
1. Arrive at www.bh.org.il, change language to hebrew.
2. Under the education section, nevigate to one of the pages listed above

Expected result:
Arrive at requested page like any other page.

Actual result:
User arrives at page but the navigation menu on the right is no longer displayed.

**Comment by nirgoldberg** [comment]
The problem is related to Hebrew items which doesn't have corresponding original items in English.
In order to fix this, a significant development should be made as I'll have to modify the way the side menu is now generated.
Another solution is to make sure all items are generated as a translation of original English items.
Please let me know your decision.

**Comment by nuritgazit** [comment]
What is the effort estimation on the second solution and who is doing it?

**Comment by nirgoldberg** [comment]
The second solution is a content based solution, should be provided by Danna. Effort estimation is depending on how many items should be generated/removed from menu. I believe you two should discuss first.

**Comment by nuritgazit** [comment]
@TheGrandVizier can you get a rough estimation from Danna without investigating too much?

**Comment by TheGrandVizier** [comment]
1. These pages are addressing hebrew speakers and have no purpose in english, so creating pages that have nothing in them is undesirable.

2. Danna says that there are changes planned for the whole "education" section, so it may not be a very good use of our time to fix this now, which is a good point i wasnt aware of.

Lets let this sit for now.

**Comment by TheGrandVizier** [comment]
Closing.
Will reopen if it becomes needed as a result of the education changes.
