### ISSUE TITLE
Blog "More" Buttons are not needed, entire item should be clickable.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#32]
Currently, the Blogs items are only accessible by clicking a small button at the bottom of the item preview.
We want the entire preview field to be clickable and take the user into the post.
The button should be kept but obviously no longer function as a button, as the entire area it's in should now do the same thing the button did.

Similar to how items' previews are entirely clickable on the Walla front page.

http://prntscr.com/fxka53

**Comment by nuritgazit** [comment]
Correction: button, title, image and sub-text should all be a link

**Comment by ibanner** [comment]
@nuritgazit May I suggest removing the button altogether? "Read More" links are an accessibility faux-pas.

**Comment by nuritgazit** [comment]
@Netush please suggest your solution

**Comment by Netush** [comment]
We can remove the Button but I would suggest that there should be some clear change on hover mode
(like zoom in on image or changing color of the title...).

**Comment by nuritgazit** [comment]
Your call, @Netush. Decide and define

**Comment by Netush** [comment]
When hover on an image it's zoom in 
& when hover on the text & title only the title change to grey color - 666666
