### ISSUE TITLE
Redirect AFBH.US into main BH site.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#33]
http://www.afbh.us/
should lead to
http://www.bh.org.il/about-us/american-friends-beit-hatfutsot/

**Comment by nirgoldberg** [comment]
Done.

**Comment by nuritgazit** [comment]
Ok, thanks.
@TheGrandVizier - please update and ask Gloria

**Comment by TheGrandVizier** [comment]
Done
