### ISSUE TITLE
Blog > blog should only show items under blog category

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#34]
In order to do so, we need to:
1. hide the menu of categories
2. Use the "blog" category as title
3. Change links to blog from all places to link to the "blog" category (footer, other?)

**Comment by nirgoldberg** [comment]
Done

**Comment by nuritgazit** [comment]
I don't see any changes on production or test

**Comment by nirgoldberg** [comment]
They will appear soon...
