### ISSUE TITLE
Blog > blog items should include writer's details

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#35]
In the bottom of each item, the details of the author should appear:
1. Name (+ links to all his items)
2. Image
3. Description

Solution should be via association of item to a writer, so that whoever submits the item can associate it with someone else

**Comment by nirgoldberg** [comment]
@nuritgazit, Shouldn't it be designed first by @Netush?

**Comment by nuritgazit** [comment]
Only if there aren't ready-made solutions from other WP blogs, @nirgoldberg

**Comment by nirgoldberg** [comment]
Of course there are, but I need at least instructions (structure, fonts, etc.) or reference to another box I should implement AS IS or with minor changes.

**Comment by nuritgazit** [comment]
@nirgoldberg @Netush please go over a few of the existing solutions for WP and decide on one. What should guide you is minimum work for Nir.
