### ISSUE TITLE
Install LiveChat 

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#38]
We want to test the livechat service in the main site, to help people find what they want, purchase tickets, get answers to questions, etc. It will be done by the people of the visitors' center. 
In order to do that we need to add this code to each page of your website right before the closing </body> tag:

<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 9034865;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>

More instructions: https://my.livechatinc.com/install-code

**Comment by nirgoldberg** [comment]
Done in test

**Comment by nuritgazit** [comment]
Currently Marketing team can't handle this, to I'm closing.
