### ISSUE TITLE
Sharing individual images (greeting cards) to facebook.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#39]
We want to have the ability to mark an image in the CMS as "sharable".
Images marked as such will be sharable by the user via normal facebook sharing tools.

This means that the shared psot will contain the URL like pertaining to this image.

**Comment by nirgoldberg** [comment]
Done.
In order to mark an image as "shareable", you need to edit it and define within its preferences a custom class named "fb-share", that will add the Facebook share button above the image.
This solution is good for any image added within the content editor, for page, post, event, etc.

**Comment by TheGrandVizier** [comment]
@nirgoldberg  is it on test or on live?

**Comment by TheGrandVizier** [comment]
Now with the new test setup, i am unable to reach the WP login.
get a 404.

**Comment by nirgoldberg** [comment]
It's on live already.
