### ISSUE TITLE
Radio buttons on donations page - minor visual disturbance

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#40]
http://prntscr.com/ghpuil

The Radio button, when selected, has a little frame around it.
The way it is right now, this frame is misaligned in relation to the radio button int he aftermath of being selected.

This goes away once other elements are interacted with or if focus is changed to another tab.

**Comment by ibanner** [comment]
@TheGrandVizier @nirgoldberg Fixed on my site. Please merge & re-check?

**Comment by ibanner** [comment]
Closing this, by order from @TheGrandVizier
