### ISSUE TITLE
ID field on donations page must be removed.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#43]
It is not common, on the internet and internationally, to request an ID number.
Some countries do not have such numbers.
In the states, no one will give you their social security number. It just doesnt work that way internationally.

The ID number field has to be removed.

**Comment by ibanner** [comment]
@TheGrandVizier This field is part of the iCount form, we have no control over this. Actually there's some conditional login that displays the field - I'm not sure what exactly (I asked them why - I'll forward the answer once I get it).

Anyway I remind you that this module is aimed mainly for Israeli citizens with Israeli back accounts. The Americans are directed to the AFBH donation page.

Do you want to close these issues or should I?

**Comment by ibanner** [comment]
This just in (from icount):

> התנאי הוא הזנה של 4 ספרות ראשונות ותקינות של מספר כרטיס אשראי.
> 
> כמו כן, אם 4 ספרות הראשונות שמזינים הוא מספר של כרטיס אשראי מחו"ל, השדה של ת.ז לא צריך לקפוץ.

**Comment by TheGrandVizier** [comment]
זה לא עניין של לקפוץ.
הוא לא צריך להופיע מלחתכילה.
נתקלנו בבעיה הזאת בעבר והיא נפתרה.
@nirgoldberg 
זוכר מה היה הפתרון?

@ibanner 
תשאיר לי בבקשה את ההחלטה מתי האישיו סגור.

**Comment by ibanner** [comment]
@TheGrandVizier I apologize - of course, I'll leave it to you to close the issues. I wasn't familiar with the way you run these things.

Anyway I've followed-up icount's answer with a question whether this is a required field for Israeli CCs. 
If it isn't required, I can hide it with CSS. If it _is_ required, I can't see how we can do something about it.

**Comment by TheGrandVizier** [comment]
Yes. I understand.
This is why i would prefer to wait for Nir's input on this as we have tackled this exact issue in the past.

**Comment by ibanner** [comment]
@TheGrandVizier @nirgoldberg icount says it's a required field for Israeli CCs and can't be removed:

> השדה הזה הוא אכן חובה ולצערי אין אפשרות להסיר אותו.

**Comment by nuritgazit** [comment]
It's ok, leave the field

**Comment by TheGrandVizier** [comment]
I dont care what they say because the fact is that field does not exist in
our other payment features, for example, store purchases.

There is no point making decisions on this before we have all the
information.
They can say its impossible all they want but the facts arent with them
here.

If we dont want to bother with it, thats another thing.

**Comment by nuritgazit** [comment]
First we launch

**Comment by TheGrandVizier** [comment]
Upon further review i must concede the feature works as intended.
