### ISSUE TITLE
Add missing financial PDFs to wordpress (Donations)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#50]
The relevant documents need to be available on the WP.
At the moment we are missing the IRS Article 46 pdf and BH Annual report.

**Comment by ibanner** [comment]
@TheGrandVizier The docs are in the shared folder on Google Drive. I'll put them on when I setup the module on production. This isn't a real issue, I think :)

**Comment by ibanner** [comment]
@TheGrandVizier @nirgoldberg This is already done, but the link to one of the DOCs is not displayed properly; I fixed it in the nest pull request
https://github.com/Beit-Hatfutsot/wp-bh/pull/57

**Comment by ibanner** [comment]
See previous comment.
