### ISSUE TITLE
Donations by Check,  Bank Transfer or Phone

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#51]
The texts for these pages are a bit simplistic and undesigned.
We should have proper texts and visuals on these "sub-pages".

**Comment by nuritgazit** [comment]
Agreed. This shouldn't postpone the launch, but it should be conveyed to Racheli, who is the customer here

**Comment by nuritgazit** [comment]
First thing, please fix the missing space under "by phone" tab

**Comment by ibanner** [comment]
@nuritgazit You mean this?
![image](https://user-images.githubusercontent.com/4220832/30542873-a38ec738-9c89-11e7-980e-53cbc2ffab41.png)

**Comment by nuritgazit** [comment]
yes, thanks

**Comment by ibanner** [comment]
fixed in #57 
(cc @nirgoldberg )

**Comment by ibanner** [comment]
@TheGrandVizier please consider assigning somebody from your content team for this, and reassigning me when you have new texts.

**Comment by nuritgazit** [comment]
@hagayk please take it from here

**Comment by TheGrandVizier** [comment]
@ibanner  it seems that these texts are not editable via the CMS.
Is there a particular reason? If not, could they be placed there?
It stands to reason thatt Hagay should be able to change these texts when he sees fit.

**Comment by ibanner** [comment]
@nirgoldberg Correct. at the moment these are hardcoded text strings. If you prefer, I can add an interface for these under the Donation Settings.

**Comment by TheGrandVizier** [comment]
Please do.
I will open a new issue for this.

**Comment by ibanner** [comment]
Text can now be entered via the admin under "Donation Options" > "Texts".
