### ISSUE TITLE
Connect test site to AdSense

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#53]
This is the code:

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1490451667276102",
    enable_page_level_ads: true
  });
</script>

Paste it into the HTML of https://www.bh.org.il, between the <head> and </head> tags

**Comment by nuritgazit** [comment]
Abort - please remove ASAP @nirgoldberg

**Comment by nirgoldberg** [comment]
Done
