### ISSUE TITLE
Donate: Limit "other sum" to a reasonable number.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#56]
Currently, the input field for a custom sum can receive any numeric input.
Since donations above a certain size have their own venue, once such value is exceeded, the flow should be halted, stopped or terminated.

@nuritgazit  please provide the numbers and what should happen next.

**Comment by nuritgazit** [comment]
Please ask Racheli

**Comment by TheGrandVizier** [comment]
I think this should be in relation to what is the biggest sum the terminal is allowed to collect.

**Comment by TheGrandVizier** [comment]
@ibanner  can we determine what is the highest sum they will allow per transaction?

**Comment by ibanner** [comment]
@TheGrandVizier I've asked icount, but I think they'll say that it depends on the terminal provider terms (Pelecard) - or even the CC companies themselves. 

Anyway when you decide on a max sum you should also decide what happens when someone tries to enter a higher number.

**Comment by ibanner** [comment]
Max sum per transaction is set in the contract you sign with the CC companies. Please either find out what it is or set an arbitrary one - and also define the UX/UI for this. Meanwhile there's nothing for me to do here... back to you, @TheGrandVizier...

**Comment by TheGrandVizier** [comment]
@nuritgazit 
Where can one find out about these contracts with CC companies?
Thisis not the first time they are mentioned. We need to know what we are dealing with.
This cannot be arbirtrary without shooting ourselves in the foot, i feel.

**Comment by nuritgazit** [comment]
I send you again to Racheli and Anna - they are the clients here, we only provide online services. They have the agreement with CC companies. Other than the technical limit by CC companies, they are the ones who should say the threshold above which they want to be in touch with donors.

**Comment by TheGrandVizier** [comment]
40,000 NIS
final.
