### ISSUE TITLE
Restore the "Volunteers" page and connect to it the link from new Donate page.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#58]
We used to have a page for volunteering in the museum.
This page needs to be restored @nirgoldberg 
and it needs to be connected to link / button on the new "Donate" page that says "Volunteer".

**Comment by ibanner** [comment]
@nirgoldberg Please notify me when it's my turn :)

**Comment by nuritgazit** [comment]
This is the restored page:
https://www.bh.org.il/about-us/volunteering/
https://www.bh.org.il/he/%D7%90%D7%95%D7%93%D7%95%D7%AA%D7%99%D7%A0%D7%95/%D7%94%D7%AA%D7%A0%D7%93%D7%91%D7%95%D7%AA-2/

@ibanner You are hereby notified

**Comment by ibanner** [comment]
@TheGrandVizier DONE.

@nuritgazit Instead of saying "thanks, but no thanks" wouldn't it be better to tell people what sort of volunteer work is available from time to time, and ask them to leave their contact details? "Just a suggestion" as they say :)

**Comment by nuritgazit** [comment]
Yes, we will improve the page, it's currently a placeholder.

**Comment by nuritgazit** [comment]
Looks like it's done, please approve and close, @TheGrandVizier

**Comment by TheGrandVizier** [comment]
Confirmded.
