### ISSUE TITLE
Donate: Connect "Join the AFBH" button to the AFBH page

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#59]
The link "Join the Friends of Beit Hatfutsot" should lead to the AFBH page on our site.
Currently it leads back to donate page.

http://test.bh.org.il/about-us/american-friends-beit-hatfutsot/

**Comment by nuritgazit** [comment]
Looks like it's done, please approve and close, @TheGrandVizier

**Comment by nuritgazit** [comment]
Looks like it's done, please approve and close, @TheGrandVizier
