### ISSUE TITLE
Change "MY STORY" tab to read "Open Databases"

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#6]
The red tab on bh.org.il should look the same as it does in the open databases site:
dbs.bh.org.il

@Netush please provide the assets

**Comment by Netush** [comment]
Link to The SVG files:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Look for this two files:
Icon_OpenData-Eng-S.svg
Icon_OpenData-Heb-S.svg

Here is Sketch:
https://projects.invisionapp.com/boards/2M2YO06NRT94F/
