### ISSUE TITLE
Events and exhibitions pages have an issue when viewed at 90% zoom or less.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#63]
**Repro**

1. Arrive at [Events](https://www.bh.org.il/events/) and / or [Exhibitions](https://www.bh.org.il/exhibitions/) page in either language.
2. Reduce zoom level to 90% (Ctrl+mouse scroll)

**Expected result:**

1. Page looks normal, at 90% zoom level.

**Actual result:**

1. http://prntscr.com/gpv05v

Notes:
The issue seems to originate from the size of the boxes marked in red in the screenshot below:
https://user-images.githubusercontent.com/15191989/41102755-46fc7a5a-6a70-11e8-9226-752e1af0ec3c.png

**Comment by nuritgazit** [comment]
@TheGrandVizier - is this bug still relevant? It looks fine on my computer

**Comment by TheGrandVizier** [comment]
Happens on browsers we deem unsupported.
