### ISSUE TITLE
Header new design

### ISSUE THREAD

**Issue by nirgoldberg** [Beit-Hatfutsot/wp-bh#65]

**Comment by ibanner** [comment]
The new header looks great - but I recommend setting the language switch to show the ALTERNATIVE language, rather than the active one. Don't you think? 
![bh_flags](https://user-images.githubusercontent.com/4220832/33650778-17dee7e2-da6c-11e7-86ff-a0847849058e.PNG)

**Comment by nuritgazit** [comment]
Agreed, can you handle it? @nirgoldberg are you ok with Itay changing it?

**Comment by nuritgazit** [comment]
@ibanner Re changing languages - we will leave it as is, since we are going to have more languages soon. Perhaps later we will have a globes or a general icon for languages. 
@nirgoldberg, please handle the directions in Hebrew header

**Comment by nirgoldberg** [comment]
Done

**Comment by TheGrandVizier** [comment]
Keeping open as reminder on education

**Comment by nirgoldberg** [comment]
It's not necessary. It's a general issue for all tabs (will work automatically whenever BH will choose to activate the education tab)
