### ISSUE TITLE
Add Donate button to new header

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#70]
The donate button should be added back to the new header on the main site and the Education site.
The shop does *not* need to have one.

The button should lead to the same pages it does on current live environment.

**Comment by nuritgazit** [comment]
and in Hebrew
תרמו לנו

**Comment by nirgoldberg** [comment]
Done

**Comment by nuritgazit** [comment]
And in English: Donate (instead of Support Us)
