### ISSUE TITLE
Stop auto-capitalizing entire titles in the Blog

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#71]
The blog titles do not require automatic all-caps.
Remove the all-caps feature and let the author of the article decide where and when to use caps in a sentence.

**Comment by nuritgazit** [comment]
@ibanner please take this

**Comment by ibanner** [comment]
@TheGrandVizier I think I get that you want the blog post titles not to be displayed in uppercase (both in the blog archive page and the blog post itself, I presume).

What do you mean by "let the author of the article decide where and when to use caps in a sentence"? Which sentence would that be? I thought we're talking about the post title here, now? Do you really want to allow certain post titles to display in uppercase while others are not?

**Comment by TheGrandVizier** [comment]
The point is not to apply any changes to the title text.
If the author decides to capitalize every word, that's up to him. if he chooses to only capitalize at the beginning of a sentence, that is also up to him. Simply don't apply any global logic on titles.
