### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#73]
In order for Alina and Danna to add Russian, we need to add the language to the test site. This way, they can start with translation to the interface

**Comment by nuritgazit** [comment]
@TheGrandVizier what is the status here, I understand its done?

**Comment by TheGrandVizier** [comment]
@dannapazprins 
Please provide @nirgoldberg  with the names of the categories in Russian so he can start building the menus.

**Comment by nirgoldberg** [comment]
Done at test env.
