### ISSUE TITLE
American donors should be redirected to Click & Pledge form (IP Based)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#74]
When detecting a users IP is American, redirect the user to the click & pledge page, as opposed to normal iCount iframe.

When the user reaches this page:
https://bh.org.il/donate/secured-payment/
He should be taken to the american iframe based on IP detection.

**Comment by ibanner** [comment]
That came up in my talks w/ @nuritgazit  but I'm afraid it won't work for us on the way back - unlike the iCount iframe (btw, not Pelecard) - the C&P page won't redirect after a successful transaction.

**Comment by TheGrandVizier** [comment]
This is something i can live with.
If they gave us money, im not worried about losing them as a user / session

**Comment by nuritgazit** [comment]
Agreed.

**Comment by ibanner** [comment]
I also agree to the principle, of course. However, my point is that the current UX is quite closely tailored to the iCount iframe and API. The C&P API is different and we can't just "switch" gateways or iframe targets by IP. 

I remind you that at the moment **we rely on the redirect** to trigger the donation certificate task email.

I proposed to make some changes in the UX to make it more generic, and allow us to accommodate both billing forms (and others in the future perhaps?). My offer to create a rough mock-up for this is still open.

**Comment by nuritgazit** [comment]
Not at the moment

**Comment by ibanner** [comment]
@nuritgazit That's fine, of course. I'm just saying that switching to an alternative iframe target won't be enough.

**Comment by nuritgazit** [comment]
Closed because this is too complicated a development. We will add a link in the AFBH page to our English donation page for those who wants to donate in an English interface, and are also from outside USA
