### ISSUE TITLE
Nobelist Site only displays 10 nobelists from recent years.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#76]
The Nobelist site does not return results for Nobelists prior and including the year 2001.
When using the slider filter, searching for individuals before 2001 produces no results.

Using the alphabitc filter also produces the same 10 individuals, nothing more.

**Comment by nirgoldberg** [comment]
@TheGrandVizier, pls attach to https://github.com/Beit-Hatfutsot/wp-nobel

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/wp-nobel#4
