### ISSUE TITLE
Temporary donation redirect via link

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#77]
We want to have a big and visible link / button for americans to click for tax deductible donations.

The link would lead here:
https://connect.clickandpledge.com/w/Form/8caebec3-d998-4ba5-83bc-a9d81a204d44?636427977193759593

**Comment by ibanner** [comment]
@TheGrandVizier This is possible via the current interface, under options > donation. Please LMK if you need help finding this  setting.
