### ISSUE TITLE
Donations contacts should support multiple recipients.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#82]
The field for setting up a contact email for incoming donation certificate requests should support multiple addresses, preferably coma delimited.
Ex:
nikolai@bh.org.il, netam@bh.org.il, nurit@bh.org.il

**Comment by ibanner** [comment]
Fixed in PR #85

**Comment by TheGrandVizier** [comment]
@nirg please push asap

**Comment by nirgoldberg** [comment]
Done
