### ISSUE TITLE
Buy Tickets button should appear in header also in smallest screen size

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#83]
It seems that during the last header change, we have caused some damage.
Apparently, the previous header displayed the Buy Tickets buttons in some mobile screens, that now it does not show it. There are complaints and decrease in tickets purchase.

The solutions is to have the button in the header in all sizes. Suggestion:
![image](https://user-images.githubusercontent.com/19633598/34077549-6ff6b6c0-e30f-11e7-9b62-47be34a1efd7.png).

This is the most urgent task for Neta and Nir (once Neta is done)

**Comment by Netush** [comment]
![header](https://user-images.githubusercontent.com/19781656/34077944-82614100-e318-11e7-94b8-1348000be268.jpg)

**Comment by nuritgazit** [comment]
Thanks, @Netush.
@nirgoldberg This is now your first priority.

**Comment by nirgoldberg** [comment]
@nuritgazit, @Netush,
Is it for regular site only?
What about shop and education (As regards to shop, it could be a little bit problem in 320px because of the cart icon)

**Comment by nirgoldberg** [comment]
Done
