### ISSUE TITLE
Add link to bh.org.il at fiume spotlight

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#89]
https://www.bh.org.il/jewish-spotlight/fiume/?page_id=1146

This page should have a link to bh.org.il

Add it at the center, bottom  of the page.

**Comment by ibanner** [comment]
@TheGrandVizier Would you like me to take care of this also, while I'm at it?

**Comment by ibanner** [comment]
@TheGrandVizier Any particular design? Do you want it on the specific page or rather in the footer, across the site?

**Comment by ibanner** [comment]
Issue moved to [Beit-Hatfutsot/wp-jcf #1](https://github.com/Beit-Hatfutsot/wp-jcf/issues/1) via [**ZenHub**](https://www.zenhub.com/)
