### ISSUE TITLE
Remove malicious links from Fiuma

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#93]
Fiuma has been hacked prior to being transfered to our posession and links to various online shops have been injected.

The injections must be removed for SEO purposes.

**Comment by ibanner** [comment]
I'm guessing the code to be cleaned is here?
https://github.com/Beit-Hatfutsot/wp-jcf

Do you want to move the issue there?
@nirgoldberg Can you send me an SQL dump?

**Comment by ibanner** [comment]
Waiting for instructions from @nirgoldberg on how you want me to deliver the clean content

**Comment by ibanner** [comment]
Clean content uploaded to Dropbox.

**Comment by nirgoldberg** [comment]
Clean DB has imported.
@TheGrandVizier, please ask Sharon (SEO) to provide a re-scan.

**Comment by TheGrandVizier** [comment]
Keeping open until rescan
