### ISSUE TITLE
Humor redirect (SEO)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#98]
אנא בצעו הפניית 301 מהכתובת הישנה של תערוכת הומור ("בקרוב"):

https://www.bh.org.il/he/event/%D7%91%D7%A7%D7%A8%D7%95%D7%91-%D7%95%D7%99%D7%94%D7%99-%D7%A6%D7%97%D7%95%D7%A7-%D7%94%D7%95%D7%9E%D7%95%D7%A8-%D7%99%D7%94%D7%95%D7%93%D7%99-%D7%9E%D7%A1%D7%91%D7%99%D7%91-%D7%9C%D7%A2%D7%95/

 

אל הכתובת החדשה:

https://www.bh.org.il/he/event/%D7%95%D7%99%D7%94%D7%99-%D7%A6%D7%97%D7%95%D7%A7-%D7%94%D7%95%D7%9E%D7%95%D7%A8-%D7%99%D7%94%D7%95%D7%93%D7%99-%D7%9E%D7%A1%D7%91%D7%99%D7%91-%D7%9C%D7%A2%D7%95%D7%9C%D7%9D/

**Comment by nirgoldberg** [comment]
Done
