### ISSUE TITLE
[CRITICAL] Error 403 (forbidden) when trying  to navigate anywhere  inside the site from a specific page.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#99]
Navigating anywhere in the site from this page:
https://www.bh.org.il/news-and-events/national-day-republic-slovenia-reception-exhibition-panel/
produces an error 403.

Easily reproduced by trying to change the language of the page.
There is no error when arriving a the page by regular navigation.

**Comment by nirgoldberg** [comment]
Solved.
I've changed the post's link to exclude the term 'love' within it :)
I've also defined 301 rewrite to the new link (https://www.bh.org.il/news-and-events/national-day-republic-slvenia-reception-exhibition-panel/).
